### PR TITLE
Erosion

### PR DESCRIPTION
**Pull request by HenryGeorgist**
staging as a pr so i can monitor more closely and review more easily

### CODE REVIEW

**Comment by HenryGeorgist** [comment]
it seems the test is failing because the resource of the json file is not local to the build. we can either simplify the test to something we define in the testing suite or we can add the resource.

**Comment by trietmnj** [comment]
Looking good now

**Comment by trietmnj** [comment]
Do you want to pull into master already? There's no logic to adapt the new DamageFunction struct to the existing DamageFunctionFamily that's directly consumed yet.

**Comment by HenryGeorgist** [comment]
no i just wanted to have a place to review the code as you work on it. This way i get notifications and can more easily review than just mining commits.

**Comment by HenryGeorgist** [comment]
i think this is ready to merge. The only thing that could be done before merge is to update the erosion_trial6.json file so that it unmarshals properly

**Pull request merged**
